#!/usr/bin/env bash
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

REPORTS_DIR="${1:-reports}"

echo ""
echo "============================================================"
echo "              SSDLC LOCAL AUDIT EXECUTIVE SUMMARY           "
echo "============================================================"
echo " [Gate 1] Unused Dependencies:"
echo "   - Java 11 (Maven):     ${REPORTS_DIR}/java-11-unused.md"
echo "   - Java 17 (Maven):     ${REPORTS_DIR}/java-17-unused.md"
echo "   - Java 21 (Maven):     ${REPORTS_DIR}/java-21-unused.md"
echo "   - Kotlin 11 (Gradle):  ${REPORTS_DIR}/kotlin-11-unused.md"
echo "   - Kotlin 17 (Gradle):  ${REPORTS_DIR}/kotlin-17-unused.md"
echo "   - Kotlin 21 (Gradle):  ${REPORTS_DIR}/kotlin-21-unused.md"
echo "   - Node.js 18 (npm):    ${REPORTS_DIR}/node-18-unused.md"
echo "   - Node.js 20 (npm):    ${REPORTS_DIR}/node-20-unused.md"
echo "   - Node.js 22 (npm):    ${REPORTS_DIR}/node-22-unused.md"
echo ""
echo " [Gate 2] Deprecated & Outdated Packages:"
echo "   - Java 11 (Maven):     ${REPORTS_DIR}/java-11-outdated.md"
echo "   - Java 17 (Maven):     ${REPORTS_DIR}/java-17-outdated.md"
echo "   - Java 21 (Maven):     ${REPORTS_DIR}/java-21-outdated.md"
echo "   - Kotlin 11 (Gradle):  ${REPORTS_DIR}/kotlin-11-outdated.md"
echo "   - Kotlin 17 (Gradle):  ${REPORTS_DIR}/kotlin-17-outdated.md"
echo "   - Kotlin 21 (Gradle):  ${REPORTS_DIR}/kotlin-21-outdated.md"
echo "   - Node.js 18 (npm):    ${REPORTS_DIR}/node-18-health.md"
echo "   - Node.js 20 (npm):    ${REPORTS_DIR}/node-20-health.md"
echo "   - Node.js 22 (npm):    ${REPORTS_DIR}/node-22-health.md"
echo ""
echo " [Gate 3] Visible CVEs (HIGH & CRITICAL):"
echo "   - Java 11 (Maven):     ${REPORTS_DIR}/java-11-cve.md"
echo "   - Java 17 (Maven):     ${REPORTS_DIR}/java-17-cve.md"
echo "   - Java 21 (Maven):     ${REPORTS_DIR}/java-21-cve.md"
echo "   - Kotlin 11 (Gradle):  ${REPORTS_DIR}/kotlin-11-cve.md"
echo "   - Kotlin 17 (Gradle):  ${REPORTS_DIR}/kotlin-17-cve.md"
echo "   - Kotlin 21 (Gradle):  ${REPORTS_DIR}/kotlin-21-cve.md"
echo "   - Node.js 18 (npm):    ${REPORTS_DIR}/node-18-cve.md"
echo "   - Node.js 20 (npm):    ${REPORTS_DIR}/node-20-cve.md"
echo "   - Node.js 22 (npm):    ${REPORTS_DIR}/node-22-cve.md"
echo ""
echo " All markdown reports generated under: ./${REPORTS_DIR}/*.md"
echo " Status: AUDIT COMPLETED (Audit mode: non-blocking)"
echo "============================================================"
echo ""
exit 0
